mysql:
  host: 43.143.53.75
  port: 3306
  db: we_a_family
  user: newuser
  password: genghao123
  log_level: dev
logger:
  level: info
  prefix: '[weafamily]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: "0.0.0.0"
  port: 8080
  env: dev
